# Generated by Django 2.2.1 on 2020-06-04 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_users', '0001_initial'),
        ('diagnostic_centers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(blank=True, max_length=250)),
                ('image', models.FileField(upload_to='lab_test_pics')),
                ('discount', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('active_status', models.CharField(choices=[('Available', 'AVAILABLE'), ('Closed', 'CLOSED')], default='AVAILABLE', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Tests',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TestOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('Full Payment', 'Full Payment'), ('Half Payment', 'Half Payment')], default='Full Payment', max_length=20, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('BKASH', 'Bkash'), ('CREDIT CARD', 'Credit Card'), ('ON SPOT', 'On Spot')], max_length=20, null=True)),
                ('booked_time_slot', models.CharField(blank=True, choices=[('10:00 AM - 2:00 PM', '10:00 AM - 2:00 PM'), ('3:00 PM - 7:00 PM', '3:00 PM - 7:00 PM'), ('8:00 PM - 10:00 PM', '8:00 PM - 10:00 PM')], max_length=20, null=True)),
                ('booked_date', models.DateField(blank=True, null=True)),
                ('order_created_at', models.TimeField(auto_now=True)),
                ('staff_check', models.BooleanField(default=False)),
                ('admin_approve', models.BooleanField(default=False)),
                ('order_confirmed', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('validation', models.BooleanField(default=False)),
                ('came_for_test', models.BooleanField(default=False)),
                ('client_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_user_order', to='custom_users.Profile')),
                ('test_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_order', to='tests.Test')),
            ],
            options={
                'verbose_name_plural': 'Test Orders',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_center', to='diagnostic_centers.DiagnosticCenter')),
            ],
            options={
                'verbose_name_plural': 'Test Categories',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_category', to='tests.TestCategory'),
        ),
        migrations.AddField(
            model_name='test',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_center', to='diagnostic_centers.DiagnosticCenter'),
        ),
    ]
